version: "3"
services:
  db:
    image: mongo
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
  client:
    build: ./client
      context: .
      dockerfile: Dockerfile
    image: lee025/go-pup
    volumes:
      - .:/client
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: 
  server:
    build: .
      context: .
      dockerfile: Dockerfile
    image: lee025/go-pup
    volumes:
      - .:/server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: 